---
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MENU_VERSION=2.0.83 #optional
      - PORT_RANGE=30000:30010 #optional
      - SUBFOLDER=/ #optional
      - NGINX_PORT=80 #optional
      - WEB_APP_PORT=3000 #optional
    volumes:
      - /path/to/netbootxyz/config:/config
      - /path/to/assets:/assets #optional
    ports:
      - 3001:3000
      - 69:69/udp
      - 8082:80 #optional
    restart: unless-stopped
