version: '3'
services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:2.12.6'
    restart: unless-stopped
    ports:
      - '192.168.2.9:80:80'
      - '192.168.2.9:81:81'
      - '192.168.2.9:443:443'
    volumes:
      - /home/docker/nginx-proxy-manager/data/:/data
      - /home/docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

networks:
  default:
    external: true
    name: ingress
